name: concrete-backup
version: git
summary: A simple and powerful backup solution
description: |
  Concrete Backup is a user-friendly backup application that helps you
  backup your important files and directories with scheduling support
  and multiple destination options.

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  concrete-backup:
    command: bin/concrete-backup
    desktop: usr/share/applications/concrete-backup.desktop
    plugs:
      - home
      - removable-media
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - system-observe
      - mount-observe
      - hardware-observe

parts:
  concrete-backup:
    plugin: nil
    source: .
    override-build: |
      # Install Poetry using the official installer (same as GitHub Actions)
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="/root/.local/bin:$PATH"
      
      # Install dependencies using Poetry (including dev dependencies for PyInstaller)
      poetry install --no-interaction --with dev
      
      # Build with PyInstaller (using poetry run, same as GitHub Actions)
      poetry run pyinstaller \
        --onefile \
        --name concrete-backup \
        --hidden-import=PyQt5.QtCore \
        --hidden-import=PyQt5.QtGui \
        --hidden-import=PyQt5.QtWidgets \
        --hidden-import=pkgutil \
        --add-data="icon.png:." \
        backup_gui.py
      
      # Copy the binary to the install directory
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp dist/concrete-backup $CRAFT_PART_INSTALL/bin/
      
      # Copy icon first
      mkdir -p $CRAFT_PART_INSTALL/usr/share/pixmaps/
      cp icon.png $CRAFT_PART_INSTALL/usr/share/pixmaps/concrete-backup.png
      
      # Copy the desktop file
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications/
      cat > $CRAFT_PART_INSTALL/usr/share/applications/concrete-backup.desktop << EOF
      [Desktop Entry]
      Name=Concrete Backup
      Comment=A simple backup solution
      Exec=concrete-backup
      Icon=/usr/share/pixmaps/concrete-backup.png
      Terminal=false
      Type=Application
      Categories=Utility;System;
      EOF
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5core5a
      - libqt5dbus5
      - libqt5network5
      - python3-pyqt5
    build-packages:
      - python3
      - python3-pip
      - python3-dev
      - build-essential
      - curl
