name: concrete-backup
version: git
summary: Backup solution
description: Backup application

base: core24
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  concrete-backup:
    command: bin/concrete-backup
    desktop: usr/share/applications/concrete-backup.desktop
    plugs:
      - home
      - removable-media
      - network
      - mount-observe
      - system-observe

parts:
  concrete-backup:
    plugin: nil
    source: .
    override-build: |
      curl -sSL https://install.python-poetry.org | python3 -
      export PATH="/root/.local/bin:$PATH"
      
      poetry install --no-interaction --with dev
      
      poetry run pyinstaller \
        --onefile \
        --name concrete-backup \
        --hidden-import=PyQt5.QtCore \
        --hidden-import=PyQt5.QtGui \
        --hidden-import=PyQt5.QtWidgets \
        --hidden-import=pkgutil \
        --add-data="icon.png:." \
        backup_gui.py
      
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp dist/concrete-backup $CRAFT_PART_INSTALL/bin/
      
      mkdir -p $CRAFT_PART_INSTALL/usr/share/pixmaps/
      cp icon.png $CRAFT_PART_INSTALL/usr/share/pixmaps/concrete-backup.png
      
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications/
      cat > $CRAFT_PART_INSTALL/usr/share/applications/concrete-backup.desktop << EOF
      [Desktop Entry]
      Name=Concrete Backup
      Comment=A simple backup solution
      Exec=concrete-backup
      Icon=concrete-backup
      Terminal=false
      Type=Application
      Categories=Utility;System;
      EOF
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5core5a
      - libqt5dbus5
      - libqt5network5
      - python3-pyqt5
    build-packages:
      - python3
      - python3-pip
      - python3-dev
      - build-essential
      - curl
